stages:
  - deploy

deploy:
  stage: deploy
  image: mcr.microsoft.com/azure-cli  # Docker image with Azure CLI and kubectl pre-installed
  before_script:
    # Login to Azure using a service principal
    - az login --service-principal --username $AZURE_CLIENT_ID --password $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID

    # Set the AKS cluster credentials
    - az aks get-credentials --resource-group $AZURE_RESOURCE_GROUP --name $AKS_CLUSTER_NAME

  script:
    # Deploy the Kubernetes manifests
    - kubectl apply -f deployment.yaml
    - kubectl apply -f canary-deployment.yaml
  only:
    - master
